spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tSVgp2yS72Ljrg3oyXo
      secret-key: YcvsAtcQuf8kdgLmA4or1hVBTmralR
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-lijie
      host: http://jumsendsms.market.alicloudapi.com
      path: /sms/send-upgrade
      appcode: 552ac12841954322acde17bf4b31b10d
      templateId: M105EABDEC
  application:
    name: gulimall-third-party

server:
  port: 30000

