server:
  port: 40000
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 192.168.200.136
    password: li158158@yt
  main:
    allow-circular-references: true

gulimall:
  thread:
    core-pool-size: 20
    max-pool-size: 200
    keep-alive-time: 200
